version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - "> 3.1.0"
  - dependency-name: husky
    versions:
    - "> 4.3.6, < 5"
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.27
    - 15.0.0
  - dependency-name: rollup
    versions:
    - 2.41.5
    - 2.42.3
    - 2.45.0
  - dependency-name: cspell
    versions:
    - 5.3.1
